[package]
name = "rdnsc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Basic DNS query command line tool. Supports bare essentials and not stuff like DNS over TLS."
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
rdns-core.workspace = true