[package]
name = "rdnsd"
version = "0.1.0"
edition = "2021"
description = "Basic DNS query command line tool. Supports bare essentials and not stuff like DNS over TLS."
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rdns = { path = "../rdns" }
tokio = { version = "1.41.1", features = ["full"] }
anyhow = "1.0"